### ISSUE TITLE
undefined local variable or method `build_sidebar'

### ISSUE THREAD

**Issue by ManojDatt** [cle61/arctic_admin#20]
After adding this gem, when i move on index i get this error:
undefined local variable or method `build_sidebar' for #<ActiveAdmin::Views::Pages::Index:0x007fa89ace59d8>
I don't know why it is showing.

**Comment by cle61** [comment]
Hello,

What is the version of `arctic_admin` and `activeadmin` ?

**Comment by ManojDatt** [comment]
arctic_admin 1.3.0
and activeadmin 2.0.0.alpha

**Comment by cle61** [comment]
do you use the branch `2-0-alpha` for arctic_admin ?

**Comment by markselby9** [comment]
Hi, this issue still exists after using branch 2-0-alpha, it seems to be caused by: https://github.com/cle61/arctic_admin/blob/2-0-alpha/lib/arctic_admin/active_admin/views/pages/bases.rb#L18

![image](https://user-images.githubusercontent.com/3454734/33802591-927ad4b0-ddb5-11e7-8006-6d91577d2ca8.png)

**Comment by markselby9** [comment]
Thanks, it would look quite unstable though, as each new commit might break... 
wait for a better combination of activeadmin and arcticadmin's versions coming up 👍
